[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
david_solana = "8DXtpG31GL4L215EeREcPhQCFgFjWcWQjX27d9XEFsRo"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
